spring:
  application:
    name: bitcoin

  datasource:
    url: jdbc:mysql://localhost/btc?serverTimezone=Europe/Budapest
    username: root
    password: root
    druid:
      max-active: 20
      filters: stat,wall



mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl